# We won't use the template over here since it's going to be a one-off http backend for this project (since we're bootstrapping the terraform state for the other projects).
# No need to make the template more complex for everything else when we can just put a little specific TF here instead.

# By default, this pipeline will run all jobs except apply on merge requests.
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - before deploy
  - deploy

variables:
  TERRAFORM_DIR: ./terraform
  TF_HTTP_USERNAME: gitlab-ci-token
  TF_HTTP_PASSWORD: $CI_JOB_TOKEN
  TF_VAR_gitlab_token: $GITLAB_AUTOMATION_TOKEN
  TF_VAR_region: us-east-1

checkov scan:
  stage: before deploy
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov
      --directory "${TERRAFORM_DIR}"
      --output cli
      --output junitxml
      --output-file-path console,checkov-report.xml
  artifacts:
    when: always
    reports:
      junit: checkov-report.xml

.before_terraform_action:
  script:
    - |
      echo "Setting up AWS OIDC credentials for Terraform..."
      echo "${GITLAB_OIDC_TOKEN}" > "${CI_BUILDS_DIR}/.oidc_token"
      export AWS_WEB_IDENTITY_TOKEN_FILE="${CI_BUILDS_DIR}/.oidc_token"
      export AWS_ROLE_ARN="${AUTOMATION_ROLE_ARN}"
      export AWS_ROLE_SESSION_NAME="gitlab-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
    - |
      echo "Terraform variables:"
      echo "  AUTOMATION_ROLE_ARN:    '${AUTOMATION_ROLE_ARN}'"
      echo "  AWS_ROLE_ARN:           '${AWS_ROLE_ARN}'"
      echo "  AWS_ROLE_SESSION_NAME:  '${AWS_ROLE_SESSION_NAME}'"
      echo "  TERRAFORM_DIR:          '${TERRAFORM_DIR}'"
      echo "  TERRAFORM_STATE_REGION: '${TERRAFORM_STATE_REGION}'"
      echo "  TERRAFORM_STATE_BUCKET: '${TERRAFORM_STATE_BUCKET}'"
      echo "  TERRAFORM_STATE_KEY:    '${TERRAFORM_STATE_KEY}'"
    - terraform -chdir="${TERRAFORM_DIR}" init

plan:
  resource_group: terraform
  stage: before deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  variables:
    # A specific account id param will be required once I setup more than one account in the org.
    AUTOMATION_ROLE_ARN: arn:aws:iam::${AWS_ACCOUNT_ID_ROOT}:role/ReifnirAutomationReadOnly
  script:
    - !reference [.before_terraform_action, script]
    - terraform -chdir="${TERRAFORM_DIR}" plan -out=planfile
  artifacts:
    paths:
      - $TERRAFORM_DIR/planfile

apply:
  resource_group: terraform
  stage: deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  variables:
    AUTOMATION_ROLE_ARN: arn:aws:iam::${AWS_ACCOUNT_ID_ROOT}:role/ReifnirAutomationDeploy
  script:
    - !reference [.before_terraform_action, script]
    - terraform -chdir="${TERRAFORM_DIR}" apply -auto-approve planfile
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
