# By default, this pipeline will run all jobs except apply on merge requests.
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - before deploy
  - deploy

checkov scan:
  stage: before deploy
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d "${TERRAFORM_DIR}" -o junitxml > checkov-report.xml
  artifacts:
    when: always
    reports:
      junit: checkov-report.xml

plan:
  stage: before deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - terraform -chdir="${TERRAFORM_DIR}" init
    - terraform -chdir="${TERRAFORM_DIR}" plan -out=planfile
  artifacts:
    paths:
      - $TERRAFORM_DIR/planfile
